#ifndef TRACER_HPP
#define TRACER_HPP

#include <filesystem>
#include <string>
#include <vector>
#include <map>
#include "yaml-cpp/yaml.h"

/**
 * @brief Generates a universally unique identifier (UUID).
 *
 * This function creates a new UUID using a random generation algorithm.
 *
 * @return A string representing the generated UUID.
 */
std::string generate_uuid();

/**
 * @brief Represents a single step in the provenance chain of a data file.
 *
 * A TraceNode captures information about an operation performed on data,
 * including input/output checksums, operation details, assumptions, and
 * environmental context.
 */
class TraceNode {
public:
    /**
     * @brief Details about the operation performed.
     */
    struct Operation {
        std::string op_class;       ///< The class of the operation (e.g., "normalization", "filtering").
        std::string method;         ///< The specific method used (e.g., "TPM", "DESeq2").
        std::map<std::string, std::string> parameters; ///< Key-value pairs of operation parameters.
    };

    /**
     * @brief Details about the input to the operation.
     */
    struct Input {
        std::string shape;      ///< The shape or dimensions of the input data.
        std::string checksum;   ///< The SHA256 checksum of the input file.
    };

    /**
     * @brief Details about the output of the operation.
     */
    struct Output {
        std::string data_class; ///< The data class of the output (e.g., "quantitative_matrix").
        std::string unit;       ///< The unit of the output data (if applicable).
        std::string checksum;   ///< The SHA256 checksum of the output file.
    };

    /**
     * @brief Details about the execution environment.
     */
    struct Environment {
        std::string language;   ///< The programming language used (e.g., "cpp", "python").
        std::string tool;       ///< The tool or script name.
        std::string version;    ///< The version of the tool.
    };

    std::string trace_id;       ///< Unique identifier for this trace node.
    std::string parent;         ///< Trace ID of the parent node in the lineage ("null" if root).
    std::string timestamp;      ///< UTC timestamp of when the operation was performed (ISO8601 format).
    std::string data_class;     ///< Data class of the input to this operation.
    Operation operation;        ///< Details of the operation.
    std::vector<std::string> assumptions; ///< List of assumptions made during the operation.
    Input input;                ///< Details of the input data.
    Output output;              ///< Details of the output data.
    Environment environment;    ///< Details of the execution environment.
    std::string ontology_version; ///< Version of the ontology used.

    /**
     * @brief Constructor for TraceNode.
     * Initializes a new TraceNode with a unique ID, timestamp, and default environment.
     */
    TraceNode();

    /**
     * @brief Saves the TraceNode to a YAML file and updates the global index.
     *
     * This method serializes the TraceNode object into a YAML file within the
     * '.traceseq/nodes' directory and updates the 'index.json' to link the
     * input and output file checksums to this trace node.
     *
     * @param input_file_checksum The SHA256 checksum of the input file associated with this node.
     * @param output_file_checksum The SHA256 checksum of the output file generated by this node.
     * @param output_file_data_class The data class of the output file.
     * @param project_root The root directory of the project.
     */
    void save(const std::string& input_file_checksum, const std::string& output_file_checksum, const std::string& output_file_data_class, const std::filesystem::path& project_root);
};

/**
 * @brief Manages operation and assumption ontologies.
 *
 * This class provides functionality to load and validate operations and
 * assumptions against predefined YAML ontology files.
 */
class Ontology {
public:
    YAML::Node operations;  ///< YAML node containing operation definitions.
    YAML::Node assumptions; ///< YAML node containing assumption definitions.

    /**
     * @brief Loads operation and assumption ontologies from YAML files.
     * @param op_path Path to the operation ontology YAML file.
     * @param assump_path Path to the assumption ontology YAML file.
     */
    void load(const std::string& op_path, const std::string& assump_path);

    /**
     * @brief Validates if an operation class is defined in the ontology.
     * @param op_class The operation class string to validate.
     * @return true if the operation class is valid, false otherwise.
     */
    bool validate_operation(const std::string& op_class) const;

    /**
     * @brief Validates if an assumption (class:value) is defined and valid in the ontology.
     * @param assump_class_value The assumption string to validate (e.g., "reference_version:grch38").
     * @return true if the assumption is valid, false otherwise.
     */
    bool validate_assumption(const std::string& assump_class_value) const;
};

/**
 * @brief Creates a new TraceNode object with specified details.
 *
 * This function serves as a factory for creating TraceNode objects,
 * populating its operational and contextual details.
 *
 * @param parent_id The trace ID of the parent node.
 * @param data_class The data class of the input data for this node.
 * @param operation_class The class of the operation performed.
 * @param operation_method The method of the operation performed.
 * @param assumptions A vector of assumptions made during the operation.
 * @return A newly created TraceNode object.
 */
TraceNode create_trace_node(
    const std::string& parent_id,
    const std::string& data_class, // This is the input data_class
    const std::string& operation_class,
    const std::string& operation_method,
    const std::vector<std::string>& assumptions
);

/**
 * @brief Validates a TraceNode against the loaded ontologies and schema.
 *
 * This function checks the consistency and validity of a TraceNode object,
 * ensuring its operation and assumptions conform to the defined ontologies.
 *
 * @param node The TraceNode object to validate.
 * @param ontology The Ontology object containing definitions for operations and assumptions.
 * @return true if the TraceNode is valid, false otherwise.
 */
bool validate_node(const TraceNode& node, const Ontology& ontology);

#endif // TRACER_HPP
